[var]
str = "Hello, world"
num = 42

[monitor.1]
cooldown = "3s"
log = "test.log"
match_log = '(?<line>.*)'
push = { test = "{{line}}" }
set = { a = 14 }
exec = 'echo str = "$str", num = "$num", arr = "$arr"'
